apiVersion: v1
kind: Namespace
metadata:
  name: animecluster
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-app
  namespace: animecluster
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ml-app
  template:
    metadata:
      labels:
        app: ml-app
    spec:
      containers:
      - name: ml-app-container
        image: gcr.io/mlops-new-447207/ml-project:latest
        ports:
        - containerPort: 5000   # Your app port
---
apiVersion: v1
kind: Service
metadata:
  name: ml-app-service
  namespace: animecluster
spec:
  type: LoadBalancer
  selector:
    app: ml-app
  ports:
  - protocol: TCP
    port: 80          # External Port
    targetPort: 5000  # Container Port
